FROM openjdk:17-jdk-slim
EXPOSE 8080
COPY build/libs/Store-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]

ARG POSTGRES_ADDON_HOST
ENV POSTGRES_ADDON_HOST ${POSTGRES_ADDON_HOST}
ARG POSTGRES_ADDON_USER
ENV POSTGRES_ADDON_USER ${POSTGRES_ADDON_USER}
ARG POSTGRES_ADDON_PASSWORD
ENV POSTGRES_ADDON_PASSWORD ${POSTGRES_ADDON_PASSWORD}
ARG POSTGRES_ADDON_DB
ENV POSTGRES_ADDON_DB ${POSTGRES_ADDON_DB}