FROM openjdk:17-jdk-slim
EXPOSE 8080
COPY build/libs/Store-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]

ARG MYSQL_ADDON_HOST
ENV MYSQL_ADDON_HOST ${MYSQL_ADDON_HOST}
ARG MYSQL_ADDON_USER
ENV MYSQL_ADDON_USER ${MYSQL_ADDON_USER}
ARG MYSQL_ADDON_PASSWORD
ENV MYSQL_ADDON_PASSWORD ${MYSQL_ADDON_PASSWORD}
ARG MYSQL_ADDON_DB
ENV MYSQL_ADDON_DB ${MYSQL_ADDON_DB}