FROM openjdk:17-jdk-slim
EXPOSE 8080
COPY build/libs/Store-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]

ARG DB_URL
ENV DB_URL ${DB_URL}
ARG DB_USER
ENV DB_USER ${DB_USER}
ARG DB_PASSWORD
ENV DB_PASSWORD ${DB_PASSWORD}